### PR TITLE
post about local tensorflow build

### PR DESCRIPTION
**Pull request by mslacken**

### CODE REVIEW

**Comment by vinzv** [comment]
Thanks for the article! :+1:

**Comment by cboltz** [comment]
https://news.opensuse.org/2020/06/19/build-tensorflow-with-cuda/ starts with a broken image, can you please fix that?

**Comment by hellcp** [comment]
It's the difference between `assets/` and `/assets/`

**Comment by vinzv** [comment]
> https://news.opensuse.org/2020/06/19/build-tensorflow-with-cuda/ starts with a broken image, can you please fix that?

Fixed in d1e10911298047b03a6638d0e367a186c8cda684

**Comment by ddemaio** [comment]
It's update @vinzv Should post pretty soon

**Pull request merged**
