### PR TITLE
Add Running WebAssembly workloads with Podman

### PR DESCRIPTION
**Pull request by alexandrevicenzi**

### CODE REVIEW

**Comment by cboltz** [comment]
Nice howto, but - is this really something that fits on news.o.o?

**Comment by ddemaio** [comment]
@alexandrevicenzi any thoughts about this? It would probably fit into the "how to use" category on https://github.com/openSUSE/news-o-o/blob/master/README.md Any additional aspect that can be added that could be a little bit more relevant.

**Comment by alexandrevicenzi** [comment]
Feel free to delete the blog post if it does not fit into it.

This new feature was introduced into Podman in Tumbleweed and also a new package.
The blog post was to show how to use it.

**Comment by ddemaio** [comment]
@cboltz what do you think? That fact it was introduced into Podman in Tumbleweed has some relevance. I could add a paragraph up front about that. Thx @alexandrevicenzi

**Comment by cboltz** [comment]
Adding such a paragraph would indeed be a good idea.

Since the article got some attention already, I wouldn't delete it - but in general such howtos would fit better on blogs or in the wiki (maybe with a link to them in the "tumbleweed monthly updates" if they are related to new features or packages).

**Pull request merged**
