### PR TITLE
openSUSE Tumbleweed available on AWS

### PR DESCRIPTION
**Pull request by cabelo**
First image openSUSE Tumbleweed available on AWS

### CODE REVIEW

**Comment by ddemaio** [comment]
Hi @cabelo Could you update the file to the yyyy-mm-dd-title.md name. It should be something like 2020-04-14-openSUSE-Tumbleweed-available-on-AWS.md Otherwise, it won't really work with the Jekyll instance.

**Comment by cabelo** [comment]
> Hi @cabelo Could you update the file to the yyyy-mm-dd-title.md name. It should be something like 2020-04-14-openSUSE-Tumbleweed-available-on-AWS.md Otherwise, it won't really work with the Jekyll instance.

Done

**Comment by guoyunhe** [comment]
Could you add a `license` for the post? Like:
```
license: CC-BY-SA-3.0
```

**Comment by vinzv** [comment]
To be honest the logo/trademark usage concerns me a bit.

1. The "aws Marketplace" logo is slightly off the [logo usage guidelines, page 38 ff](https://s3.amazonaws.com/awsmp-loadforms/AWS_MP_GTM_ProgramGuide.pdf).

2. The "EC2" logo seems to have gotten renewed by Amazon? ([Source](https://en.wikipedia.org/wiki/Amazon_Elastic_Compute_Cloud))

3. That added shadow at the EC2 logo was added by you, right? I don't think that's according to Amazon's guidelines.

Sorry to be a bit picky here but we don't want to mess with other's trademarks in a way that is not in their sense.

**Comment by cabelo** [comment]
> Could you add a `license` for the post? Like:
> 
> ```
> license: CC-BY-SA-3.0
> ```

Done

**Comment by cabelo** [comment]
> To be honest the logo/trademark usage concerns me a bit.
> 
>     1. The "aws Marketplace" logo is slightly off the [logo usage guidelines, page 38 ff](https://s3.amazonaws.com/awsmp-loadforms/AWS_MP_GTM_ProgramGuide.pdf).
> 
>     2. The "EC2" logo seems to have gotten renewed by Amazon? ([Source](https://en.wikipedia.org/wiki/Amazon_Elastic_Compute_Cloud))
> 
>     3. That added shadow at the EC2 logo was added by you, right? I don't think that's according to Amazon's guidelines.
> 
> 
> Sorry to be a bit picky here but we don't want to mess with other's trademarks in a way that is not in their sense.

EC2 logo was removed

**Comment by lnussel** [comment]
AWS images are not part of openSUSE:Factory, as such those images are not official. Means they need approval for using the openSUSE trademark, see https://en.opensuse.org/openSUSE:Trademark_guidelines#Distributing_openSUSE_With_Modifications

Was such approval given by the board? If not I'd suggest to withdraw the news item and openSUSE branded AWS offering ASAP.

@cabelo would be really cool to get those images into Factory to have them official though! We can help you with that if you are interested of course.

**Comment by cboltz** [comment]
Bonus question: The article uses the Heroes logo, but AFAIK the AWS image is unrelated to the Heroes or the openSUSE infrastructure. I'd recommend to use a different picture - for example, the Tumbleweed logo might be a better choice.

**Pull request merged**
