### PR TITLE
Ritchie-CLI for openSUSE

### PR DESCRIPTION
**Pull request by cabelo**

### CODE REVIEW

**Comment by cabelo** [comment]
Sorry for the confusion of the previous PR.

**Comment by vinzv** [comment]
Thanks, now everything looks in place! :)

**Comment by lnussel** [comment]
The referenced package is just a home repo so it never saw any review or quality checks. Please withdraw this article. Users are not supposed to add random home repos. The article can be published once the package went through all quality gates and got included into the distro.

**Comment by vinzv** [comment]
I don't see why that would be necessary. As long as there is no claim that 
the packages are official ones and "made by openSUSE".

**Comment by lnussel** [comment]
Do I really need to explain why training people on adding random home repos isn't a good idea? I'm sure google will find better explanations. If we wanted to promote packages then please those that went the extra mile to make sure they pass the quality gates, license review etc and therefore got accepted into the official repo. If the package promoted here is fine there's nothing that would prevent it from going to Factory. So please do that first, then publish the article.

**Comment by cabelo** [comment]
> The referenced package is just a home repo so it never saw any review or quality checks. Please withdraw this article. Users are not supposed to add random home repos. The article can be published once the package went through all quality gates and got included into the distro.



> The referenced package is just a home repo so it never saw any review or quality checks. Please withdraw this article. Users are not supposed to add random home repos. The article can be published once the package went through all quality gates and got included into the distro.

@lnussel 

The mistake was all mine, I didn't know this rule and it makes sense.

I doing try to get the ritchie packge into factory.

I don't want to promote packages, I didn't do the ritiche. I'm just recognizing the work of a community.

excuse me.

**Pull request merged**
