### PR TITLE
Ritchie-CLI 2.11.3 version

### PR DESCRIPTION
**Pull request by cabelo**

### CODE REVIEW

**Comment by cboltz** [comment]
May I remind you to the news.o.o README which says `Articles out of scope, in particular written to promote packages or home repositories, are discouraged`?

Announcements of new packages should go to your personal blog (ideally aggregated on planet.o.o) and/or to the factory mailinglist.

**Comment by ddemaio** [comment]
I think there is some room to work with here. @cabelo When did the package become official in Tumbleweed? @cboltz, I can see a news element to this if in fact it is announcing that it's now official in Tumbleweed. What do you think?

**Comment by cabelo** [comment]
> to promote packages or home repositories
Hello everyone

The Package is not in my home repository. Ritchie-CLI is now on 
https://build.opensuse.org/package/show/openSUSE:Factory/ritchie-cli

**Comment by cabelo** [comment]
> I think there is some room to work with here. @cabelo When did the package become official in Tumbleweed? @cboltz, I can see a news element to this if in fact it is announcing that it's now official in Tumbleweed. What do you think?

Thanks @ddemaio 

I'm creating a blog in english specifically for this: https://innovatorsforopensuse.org/

Because every post I create generates a lot of controversy and I actually just want to help spread the word about openSUSE technologies. All of this turns out to be disheartening. All of this turns out to be disheartening.

I don't want to divulge my personal repository, because I don't need it and I don't want to.

**Comment by cabelo** [comment]
> When did the package become official in Tumbleweed?

15 days the last change was completed.
But just yesterday I finished all the on-premise and cloud testing https://aws.amazon.com/marketplace/pp/B086VDH9KM .

**Comment by ddemaio** [comment]
Thank you @cabelo I appreciate your contributions. I can understand the frustration. I still want to publish this, but want to have another person agree as I see there being some news value here. I also take it that your reference to "my OBS home project available to all openSUSE users interested in testing." is that you're using that specifically for building and testing new features and will push those to official. @vinzv Do you have any input here.

**Comment by KaratekHD** [comment]
I can see the arguments of both sides. Maybe we could close this PR and instead publish this in one of these posts that contain what's new in Tumbleweed? That would be the best solution in my opinion, as it does not create an extra news article yet is still den by the community.
~ Jens

**Comment by ddemaio** [comment]
Great idea @KaratekHD I think that provides a good solution.

**Comment by cabelo** [comment]
Thank you @KaratekHD  and @ddemaio

**Pull request closed without merging**
