### PR TITLE
ADD Gaussian and Neural Accelerator Library

### PR DESCRIPTION
**Pull request by cabelo**

### CODE REVIEW

**Comment by cboltz** [comment]
At the risk of getting hated: This looks more like advertising than like something that should be on news.o.o.

Alessandro, IMHO articles like this fit much better in your personal blog. (Which, if you want, can be aggregated on planet.o.o.)

**Comment by ddemaio** [comment]
@cboltz we've published a few of these from @cabelo in the past. It does focus on innovation specific to the project, so I believe it falls in line with the rules we put on the readme. It also says that certain articles "may be subject to the removal". So we can remove it if you think it's out of scope.

**Comment by cboltz** [comment]
I know that we had a few similar articles before, and more than once, I raised an eyebrow about them. I also remember someone else on the marketing list who stated that they'd better fit to a personal blog instead of having them on news.o.o.

I'd summarize this article as "Intel has some shiny new hardware, and openSUSE runs on it". That's why I called it advertising. (If every company with shiny new hardware that can also run with openSUSE (basically every new laptop, server, ...) would write an article on news.o.o, well, we'd have quite some articles ;-)

It's also interesting that you need some additional software and even a kernel module (see the wiki page linked in the article) to fully use that shiny new hardware - and the wiki page says that you need to wget or git clone and then compile it. The news.o.o readme discourages mentioning home repos, and while it doesn't have a specific rule *) about needing git repos and a compiler, "not even packaged" is much worse than a package from a home repo. (I don't even want to think about the possible security implications caused by loading that kernel module - no idea if it got any review etc. and/or if you can trust the people running the server where it's hosted.)

*) I guess you heard the story about the manual for microwaves, which didn't include a specific rule that you shouldn't use the microwave to dry your dog...

I'm also quite sure that the additional software you need is not specific to openSUSE, therefore I'd also question "innovation specific to the project". (Since it works with both Leap and Tumbleweed, I guess you could simply replace openSUSE with other distros in the text, and it also works there.)

That leaves us with the possible removal. I clearly vote for it, but unfortunately it comes with some side effects, like having tweets pointing to a no-longer existing article. Therefore "not (instantly) publishing and thinking twice" would have been much better than removing an already-published article.

Now do whatever you want ;-)

@cabelo: Sorry if this sounds discouraging. It's not meant that way, it's "just" that news.o.o is not the place for such articles IMHO. Please use your personal blog and post things like this there. (If you add an english category/feed to your blog or setup a separate english blog, I'll happily add it to the english section of planet.o.o.)

**Comment by ddemaio** [comment]
@vinzv could you provide another view on this so we can have a decision. @cboltz does make some valid points on the compiling aspects. Just want another view in order to make a decision on this one. I agree with @cboltz not to discourage the contribution to news.o.o. as it would be nice to have more articles.

**Comment by vinzv** [comment]
As I did in the past already I'd prefer having those kind of articles on planet.o.o. IMHO news.o.o is for news from the openSUSE community like new projects, initiatives, Tumbleweed weekly reports etc.

**Pull request merged**
